// Code generated by "stringer -type=UserStatus"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unverified-0]
	_ = x[Verified-1]
	_ = x[Suspended-2]
}

const _UserStatus_name = "UnverifiedVerifiedSuspended"

var _UserStatus_index = [...]uint8{0, 10, 18, 27}

func (i UserStatus) String() string {
	if i < 0 || i >= UserStatus(len(_UserStatus_index)-1) {
		return "UserStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UserStatus_name[_UserStatus_index[i]:_UserStatus_index[i+1]]
}
